// test-workspace/vue-app/src/components/PostDetail.vue
<script setup lang="ts">
import { gql } from "@apollo/client";

const GET_POST = gql`
  query GetPost($id: ID!) {
    post(id: $id) {
      id
      title
      body
      author {
        id
        name
      }
    }
  }
`;

const CREATE_POST = gql`
  mutation CreatePost($title: String!, $body: String!) {
    createPost(title: $title, body: $body) {
      id
      title
    }
  }
`;

defineProps<{ postId: string }>();
</script>

<template>
  <article>
    <h1>Post Detail</h1>
    <p>{{ postId }}</p>
  </article>
</template>

// test-workspace/svelte-app/src/lib/PostDetail.svelte
<script context="module" lang="ts">
  import { gql } from "graphql-tag";

  export const POST_FRAGMENT = gql`
    fragment PostFields on Post {
      id
      title
      body
    }
  `;
</script>

<script lang="ts">
  import { gql } from "graphql-tag";

  const GET_POST = gql`
    query GetPost($id: ID!) {
      post(id: $id) {
        ...PostFields
        author {
          id
          name
        }
      }
    }
  `;

  export let postId: string;
</script>

<article>
  <h1>Post Detail</h1>
  <p>{postId}</p>
</article>
